leanuservices:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./wordpress:/var/www/html
        depends_on:
            - php
            - wordpress
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: devops/php/Dockerfile
        volumes:
            - ./wordpress:/var/www/html
        networks:
            - app-network

    wordpress:
        build:
            context: .
            dockerfile: devops/wordpress/Dockerfile
        env_file:
            - .env
        volumes:
            - ./wordpress:/var/www/html
        depends_on:
            - mysql
        networks:
            - app-network

    mysql:
        image: mysql:latest
        env_file:
            - .env
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network

    node:
        image: node:latest
        volumes:
            - ./wordpress:/usr/src/app
        working_dir: /usr/src/app
        command: npm start
        ports:
            - "3000:3000"
        networks:
            - app-network

volumes:
    mysql-data:

networks:
    app-network:
        driver: bridge